### ISSUE TITLE
Data is not persistent

### ISSUE THREAD

**Issue by jabirmayar** [lesnitsky/flutter_localstorage#78]
Data gets lost on hot restart or after restarting the application. 

```
await storage.ready;
storage.getItem('item'); 
```
is not working.

**Comment by Dobbychen** [comment]
Experiencing the same from android

**Comment by Colin-XKL** [comment]
same question, tested on windows

**Comment by Colin-XKL** [comment]
fixed.  
see https://github.com/lesnitsky/flutter_localstorage/issues/49#issuecomment-676146168  
the author should mention it in the official doc in pub.dev 😅

**Comment by jabirmayar** [comment]
> 
> 
> Experiencing the same from android
any news???




> 
> 
> fixed.
> see [#49 (comment)](https://github.com/lesnitsky/flutter_localstorage/issues/49#issuecomment-676146168)
> the author should mention it in the official doc in pub.dev 😅

Well, i tried that as you can see code in the start but the issue for me is not resolved.

**Comment by lesnitsky** [comment]
@jabirmayar please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jabirmayar** [comment]
Sorry, I tried and it worked in another project. There was a problem with one of my data fields. Closing this.
